const TEXT_SIZES = {
  FONT_H0: 50,
  FONT_H1: 40,
  FONT_H2: 35,
  FONT_H3: 30,
  FONT_H4: 25,
  FONT_H5: 20,
  FONT_H6: 15,
  FONT_H7: 10,
};

const LAYOUT_SIZES = {
  MARGIN_LEFT: 15,
  MARGIN_RIGHT: 15,
  MARGIN_TOP: 15,
  MARGIN_BOTTOM: 15,
  PADDING_HORIZONTAL: 15,
  PADDING_HORIZONTAL_HUGE: 25,
  PADDING_VERTICAL: 15,
};

const ICON_SIZES = {
  ROUND_BUTTON_ICON: 27,
  BANNER_ICON: 15,
  CHEVRON_ICONS: 30,
  CHEVRON_ICONS_SMALL: 15,
  BUTTON_ICONS: 35,
  BUTTON_ICONS_EVENT: 45,
};

export {TEXT_SIZES, LAYOUT_SIZES, ICON_SIZES};
